### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by EsTaNG9** [Sunekaer/stoneBlock#106]
When I try to start the server it simply crashes, closing the prompt where minecraft loads.

Heres the full log:  https://pastebin.com/n2CGvDHE

My system information:

- Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-30-generic x86_64)
- Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
- 2x4GiB DDR3 1600 MHz

Thank you for your help

**Comment by EsTaNG9** [comment]
I doesn't generate an crash log as far as I know. 
The only logs that it generates after suddenly closing the prompt is debug.log (the one that I posted above) and latest.log (https://pastebin.com/bqThCtq2), nothing more.

Thank you

**Comment by EsTaNG9** [comment]
That cannot be right because I don't have an GPU on my server. Is there any drivers for Intel integrated graphics? If there is I'll try to update it.
Thank you

**Comment by Sunekaer** [comment]
No problem, let me know what you find out

**Comment by EsTaNG9** [comment]
Well, it still doesn't generate an crash log and it also didn't solve the problem. The log is pratically the same.

**Comment by Sunekaer** [comment]
please upload the full log to https://gist.github.com and link it

**Comment by EsTaNG9** [comment]
Here is debug.log (https://gist.github.com/EsTaNG9/f6b8a44b594ebd901cf4c99be90cc59c) and latest.log (https://gist.github.com/EsTaNG9/cae8cbd075d0a47d20a433666a365d7e)
Thank you for all the help

**Comment by Sunekaer** [comment]
I don’t know how to fix this..

Just know that this is the problem 
Caused by: java.awt.AWTError: Can't connect to X11 window server using 'localhost:11.0' as the value of the DISPLAY variable.

**Comment by Sunekaer** [comment]
Maybe some x11 driver or something?
Are you using windows server or just a normal windows 10?

**Comment by tlemaillet** [comment]
@EsTaNG9 Just guessing, but if you are launching your server on a headless linux machine, you need to launch the forge server with the "nogui" argument appended to the command line you are using, else it will try to find a valid X11 server that isn't here to display the minecraft server window.

**Comment by EsTaNG9** [comment]
So after many failed tries I decided to virtualize an Windows Server and it worked. In the future I'm putting an GTX 650 TI BOOST on my server and then I'll try again. In conclusion I'm closing the threat because I'm sure the problem is with my machine and not with the modpack besides that I really missed that line @Sunekaer so I might be very blind, regardless, thank you for all the help and attention.

**Comment by tlemaillet** [comment]
@EsTaNG9 My hosting server only has a 2D graphic card, so that's probably not the issue.
You are using Ubuntu so i invite you to read about X and X.org : https://en.wikipedia.org/wiki/X_Window_System .
TL;DR : X.org is an application running on your computer allowing graphical applications to be displayed.

In general, if you are running applications on a machine which has no display (headless machines and/or servers for example), some programs will still try to display something by default, and fail while trying to reach the X11 compatible server application (X.org) running on said machine.
Leading to this line: `Can't connect to X11 window server using 'localhost:11.0' as the value of the DISPLAY variable.`

The `DISPLAY` environment variable allows to manually tell programs on which display server they should use, and you can use it to point to a correct display server should one be present on the machine you are trying to use.
The second option is to tell the program not to display anything, and in the case of a minecraft server translate to the `nogui` command line option.
