### ISSUE TITLE
Crashing on Launch

### ISSUE THREAD

**Issue by GCPleb** [Sunekaer/stoneBlock#144]
**Bug Report**
Steps to Reproduce (for bugs):
Open the modpack and run the modpack as it is loading it crashes around 4/7 loading

**Logs**
Client/Server Log:
Crash Log:https://gist.github.com/GCPleb/b56a90c1f6bee990affb30c3fc829ce4
**Client Information**
Modpack Version:1.0.15
Server/LAN/Single Player: Single Player
Optifine Installed: N
Shaders Enabled: N

**Comment by Sunekaer** [comment]
Okay so its craftpresence causing the issue, as you only play single player you can just disable that mod

**Comment by GCPleb** [comment]
The modpack doesn't launch at all so all I have to do is just delete the mod correct?

**Comment by Sunekaer** [comment]
in the launcher under installed mods find it and in the left site there is a "on/off" button

**Comment by Sunekaer** [comment]
https://gitlab.com/CDAGaming/CraftPresence/issues/5

**Comment by GCPleb** [comment]
Perfect works now thanks for the help man

**Comment by CDAGaming** [comment]
The Original Issue her is due to an Invalid DLL (Oddly, this was only a case in the Original Releases of CraftPresence, fixed when I replaced the DLLs with Verified Ones)

GCPleb, can you do the following and see if your Issue is resolved:
1) Go into your Packs .Minecraft/Main Folder. You should see a "CraftPresence" folder
2) Remove the Folder
3) Launch the Pack again with CraftPresence to have the Mod regenerate the Libraries

Let me know if this works or if you experience the same crash
