### ISSUE TITLE
FML detected the backup level.dat is being used

### ISSUE THREAD

**Issue by AlleinSoldat** [Sunekaer/stoneBlock#224]
I travel a lot so I use my laptop consistently. So, I transfer all of my progress between my laptop and my desktop. The save game I used first on my desktop after update and it's throwing that error. If I click yes on it, it replaces blocks I've places with either air or some random block like stairs. I have attached screenshots. If I revert back to version 1.0.16, everything works just fine on both computers.

Steps to Reproduce (for bugs)

1. Transfer save game from one PC to another
2. Open save in game

Client Information
Modpack Version: 1.0.17
Server/LAN/Single Player: SSP
Optifine Installed: Nope
Shaders Enabled: Nope

![stoneblock fml error](https://user-images.githubusercontent.com/30380842/46262280-df56d500-c4b3-11e8-9e39-c511e32dcbe1.PNG)

![2018-09-30_13 22 10](https://user-images.githubusercontent.com/30380842/46262285-f695c280-c4b3-11e8-9a83-af35819393ba.png)

**Comment by Sunekaer** [comment]
what blocks from what mods has been removed?

**Comment by TigerWalts** [comment]
I have been dealing with the same issue.

It's considering the FML data in `level.dat` to be invalid. It falls back to the `level.dat_old`. That one also fails but it retains the `Data` node but rebuilds the `FML` and `forge` nodes. But because it considers the old FML data to be invalid it ignores it and also skips converting block ids in the region files.

Looking at the `level.dat` file from before and after updating, a lot of id/index numbers that blocks are registered with have changed, there are 6 more blocks and they would all been assigned ids anew.

You may want to check if this is a known issue with certain Forge versions.

**Comment by tjd46** [comment]
I think @TigerWalts is right as if I add https://minecraft.curseforge.com/projects/notenoughids even my old world loads right up fine.

**Comment by Sunekaer** [comment]
does it work for you adding https://minecraft.curseforge.com/projects/notenoughids @AlleinSoldat ?

**Comment by AlleinSoldat** [comment]
Haven't had a chance to try. I was stuck at work all day yesterday. I'll give it a shot right now and report back.

**Comment by AlleinSoldat** [comment]
Seems to work with the addition of notenoughids. Thanks for the help everyone!

**Comment by Sunekaer** [comment]
1.0.18
