### ISSUE TITLE
Returning from deep dark places you in lava at y255

### ISSUE THREAD

**Issue by billyty08** [Sunekaer/stoneBlock#272]
## Bug Report
Use portal to return from deep dark to overworld placed me at build limit in the lava at the coordinates of the portal block in overworld.
## Steps to Reproduce (for bugs)

1.It happens to this youtuber at the 29 minute mark
2.https://www.youtube.com/watch?v=FJeAmK0rVC4

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:1/0/17
* Server/LAN/Single Player:
* Optifine Installed:no
* Shaders Enabled:no

**Comment by Almagnus1** [comment]
I'm also seeing this issue on load, as I'm trying to load into 653, 244, 585... which isn't working >.>

I'm not sure if unlocking the profile and updating Extra Utilities to v 1.12-1.9.8 or creating a new world did this, but hopefully the Extra Utilities update is a viable workaround for this issue.

**Comment by OfficialStamper** [comment]
Making a bed and setting a spawn point will then return you to your bed.  Default spawn point is world spawn, which will put you in lava as the default spawn point.

**Comment by Almagnus1** [comment]
I saw that off of creating a new world, and I basically lagged out as I was loading an infinitely big lava field as I had essentially spawned above world height.

While it's a cool thing that there's lava up there, perhaps the modpack should have the top layer be bedrock, and then the level below that be lava, and then from there until the bottom of the world be stone down to bedrock at the bottom.  That would at least mitigate this issue, and if someone does end up above the world, they aren't lagged out due to Minecraft derping with fluid stuff.

**Comment by Algester** [comment]
But you would still to mine the void to get your solar panel quest line from enviromentalcraft

**Comment by Sunekaer** [comment]
Closing issue as there cant be done anything about until the mod dev fixes the issue
