### ISSUE TITLE
Minecraft "is not responding" when I searching items with NEI 

### ISSUE THREAD

**Issue by dickensone** [Sunekaer/stoneBlock#305]
When i scroll item pages in NotEnoughItems Minecraft "is not responding" on 17 or 18 page.
Also when i typing in search panel "@a...", modpack "is not responding".

I tried to update Java and nvidia drivers.
Tried stoneBlock-1.0.17 and 18, no changes.

**Comment by Sunekaer** [comment]
How fast do you scroll and how much ram do you have assigned? i just tested om my pc and i do not have this problem

**Comment by dickensone** [comment]
Well, after "crush", when i reload game and open inventory, it freezes immediately. I assign 6gb ram of 8.
Here's a screenshot with freeze.

![image](https://user-images.githubusercontent.com/43991781/46735005-8ea65f80-cc9d-11e8-81f6-d9e4aed6fe41.png)

**Comment by knoxhack** [comment]
To be able to found out whats causing this you need to do:|
1.Load Minecraft
2.Replicate freeze
3.Once freezes again close minecraft.
4.Open your /logs folder
5.Post your latest-log file.

**Comment by angelnc1989** [comment]
I have this issue too. I think it is related to the amount of different items in the system.
Once I trashed the hundreds of armor pieces from my mob farm it got way better. Now that I'm a few hours deeper in and have almost every resource automated the issue is worse than ever. Freezing every 5 seconds.

**Comment by dickensone** [comment]
Problem was because of "ore dictionary" in NotEnoughItems settings.
