### ISSUE TITLE
Netherstar seeds (mystical addons) won't grow

### ISSUE THREAD

**Issue by Sabster** [Sunekaer/stoneBlock#411]
## Bug Report
Mystical Addons Netherstar seeds aren't growing...  You also can't use Fertilized Essence on them (obviously, since they won't grow...)  :)

## Steps to Reproduce (for bugs)
1. Plant a Netherstar seed - and see nothing happen.

## Client Information
* Modpack Version: 1.0.22r1
* Server/LAN/Single Player: Server
* Optifine Installed:  No (unless it's in the modpack. ie. I didn't add it.)
* Shaders Enabled:  No

**Comment by xkatsuro** [comment]
did you out a nether star crux under the farmland where the seed is planted? in order to grow nether star seeds or dragon egg seeds you need the corresponding crux. look for the crafting recipes.

**Comment by knoxhack** [comment]
so is this invalid issue?

**Comment by xkatsuro** [comment]
> so is this invalid issue?

I am confident that he (author of the issue post) simply didn't meet the requirements. Also I assume he's not proficient enough with JEI, since not only recipes are shown in there, conditions to be met are as well. So far, every version of the pack I've played, nether and dragon egg seeds grow just fine as long as all of the preps necessary were made.

**Comment by Sunekaer** [comment]
As xkat said remember Crux

**Comment by Abion47** [comment]
I can confirm that the seeds won't grow unless there is a crux underneath the farmland. However, even with the crux, you still can't use Fertilized Essence or Mystical Fertilizer on it.

**Comment by Chew** [comment]
@Abion47 there's a config value for that, it's false by default
