### ISSUE TITLE
when i move things around in inventories upon relog they revert to previous locals

### ISSUE THREAD

**Issue by slarzyer** [Sunekaer/stoneBlock#489]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Server/LAN/Single Player:
* Optifine Installed:
* Shaders Enabled:

**Comment by slarzyer** [comment]
also it causes things to dup if i keep it on me.....

**Comment by slarzyer** [comment]
it also cause things to dup if i keep them on me!!!

**Comment by slarzyer** [comment]
yea my inventory is totally screwed now cant store much of anything with any success.

**Comment by nzminecraftDOTcom** [comment]
Fill out the form

**Comment by slarzyer** [comment]
i have no info i logged on its bugged

**Comment by nzminecraftDOTcom** [comment]
Then we can't help you.

**Comment by Sunekaer** [comment]
have you changed ANY settings?

**Comment by Sunekaer** [comment]
Does it happen in another world?

**Comment by OfficialStamper** [comment]
this sounds like a corrupted chunk, can you save items in a chest in a different chunk?

My reason for mentioning this, is that I have had 4 corrupted chunks on my server since playing the pack and I have had to resort to deleting the offending chunks via NBTExplorer and then rebuilding them.  this is similar to what 'SystemCollapse' experienced in one of his videos...... https://youtu.be/M_klBRhDj3U

I am still trying to identify the cause and have so far narrowed it down to either the RFTools Builder or the TorchMaster Feral Flare Lantern, or a combination of both, or it could be something else.  I will post my findings once I have something more substantial than an educated guesses.
