### ISSUE TITLE
solar and lunar issue

### ISSUE THREAD

**Issue by kourgath** [Sunekaer/stoneBlock#54]
modpack includes solar and lunar panels and quests to create them but there is no sunlight or moonlight to use them

**Comment by Sunekaer** [comment]
go to the top of the world if you want to use them 
Just because there is quest for them doesn't mean you have to use them, its there to tell you that you can use them

**Comment by RobertLSnead** [comment]
Go to the miner dimension! ;)
The top of the world is all lava lol.

**Comment by mskoczen** [comment]
Just because it starts lava doesn't mean it has to stay that way. I used a fire resist to make a small safe place, and later cleared a large area with the builder and pump card. Warning for safety use a clearing card impossible to light the tops of blocks at the build limit I got massive spawns on the dirt from the plain pump card.
