### ISSUE TITLE
ModPack crashes every time I start it up, it says its due to Extra Utilities 2

### ISSUE THREAD

**Issue by shadic105** [Sunekaer/stoneBlock#58]
## Bug Report

Anytime I start up the pack, it crashes when trying to load Extra Utilities 2.
## Steps to Reproduce (for bugs)

1. Click play
2. Modpack crashes

## Logs

* Crash Log: https://pastebin.com/A9RGKsfs

## Client Information

* Modpack Version: 1.0.12
* Server/LAN/Single Player: Pack wont even start
* Optifine Installed: no
* Shaders Enabled: no

**Comment by argyllfinnegan** [comment]
It looks like it is an issue within all modpacks using extra utilities: https://minecraft.curseforge.com/projects/extra-utilities

**Comment by Sunekaer** [comment]
Mod bug
https://github.com/rwtema/Extra-Utilities-2-Source/issues/159

**Comment by RandomLibrarian** [comment]
Same issue :( A fresh install doesn't even fix this problem. Not sure why some of my PC work fine and others don't all of a sudden. What could have changed since yesterday?

Original Install worked fine yesterday: https://pastebin.com/hYnBTegF
Fresh install as of today: https://pastebin.com/5e67CN2Y
