### ISSUE TITLE
Bug craft Futura block = wired moden

### ISSUE THREAD

**Issue by Nicocraft05** [Sunekaer/stoneBlock#66]
Bug craft Futura block = wired moden

**Comment by Nicocraft05** [comment]
good texture for me just modification the craft?

**Comment by kosherbacon79** [comment]
I just tested this in a 1.0.13 world:

You can craft Futura block by using Chiseled Stone, instead of regular Stone. I've attached a screenshot to show you.
![futura](https://user-images.githubusercontent.com/42524845/44359711-a8d67500-a486-11e8-9a94-06d8b2785e51.png)


The textures are no longer buggy. That must have been fixed in a previous update.

**Comment by Sunekaer** [comment]
recipe conflict not "bug"

**Comment by kosherbacon79** [comment]
Where is the best place to report recipe conflicts?

**Comment by Sunekaer** [comment]
1.0.14

**Comment by Nicocraft05** [comment]
I add here the wireless crafting terminal it is impossible to launch a craft

**Comment by Nicocraft05** [comment]
and nice modpack thank you continue

**Comment by Sunekaer** [comment]
This issue is closed make a new one..
