### ISSUE TITLE
World Loading In

### ISSUE THREAD

**Issue by SMASH-DIAMOND** [Sunekaer/stoneBlock#671]
## Bug Report

World will never stop Loading in.
## Steps to Reproduce (for bugs)

1.Open StoneBlock
2.Start A New world

## Logs

* Client/Server Log:[(https://paste.feed-the-beast.com/view/0c08831a)]
* Crash Log:[(https://paste.feed-the-beast.com/view/5d4d516b)]

## Client Information

* Modpack Version:Latest
* Server/LAN/Single Player:Single Player, Have Issues with starting my server thats with Aternos woking that out with them.
* Optifine Installed:No Unless in ModPack
* Shaders Enabled:None
Also I've tried To re download it.
## Computer
Mac mini (Late 2012)
Processer 2.5 GHz Intel Core i5
Memory 16 GB 1600 MHz DDR3
Graphics Intel HD Graphics 4000 1536 MB
Also 16 RAM

**Comment by SMASH-DIAMOND** [comment]
Better

**Comment by Tommsy64** [comment]
This line `java.lang.OutOfMemoryError: Java heap space` means that the game is crashing because it is running out of RAM.
This line `JVM Flags: 3 total; -Xmx3072m -Xms256m -XX:PermSize=256m` shows that the game is being launched with only 3 gigabytes maximum of RAM.

In the Twitch settings, make sure the amount of RAM is at least 5 or 6 gigabytes. 8 is ideal.

![image](https://user-images.githubusercontent.com/3900951/49124859-f6cff580-f28b-11e8-94f9-cda34e3021e9.png)

**Comment by Sunekaer** [comment]
Answered by tommsy
