### ISSUE TITLE
Server Issues.

### ISSUE THREAD

**Issue by ThePuffingMoose** [Sunekaer/stoneBlock#676]
## Bug Report
Everytime i try to join the server it tells me every single mod that is currently in the pack and what version of the mod i need in order to join the server. Which every mod is either outdated or a higher version than the current one in the pack.

## Client Information
* Modpack Version: 1.0.30
* Server/LAN/Single Player: Server
* Optifine Installed: No
* Shaders Enabled: No

**Comment by CastielAngelow** [comment]
Are you 100% sure server is same version as your modpack? :)

**Comment by nzminecraftDOTcom** [comment]
You are running an incorrect version of the pack, re-install with the correct version for the server and you should be fine.

**Comment by Sunekaer** [comment]
as said above make sure your running the same version as the server

**Comment by ThePuffingMoose** [comment]
How do I install the server version modpack? Ive tried that last night and it only gave me some folders which i did replace in the modpack and that didnt work either.

**Comment by CastielAngelow** [comment]
Installing server is a bit more complex. First of all, depending on where you run actual server? If its going to be your computer, download server files. If its not inside, download server.jar. btw., theres plenty of tuts. Just keep it clean / closed.

**Comment by nzminecraftDOTcom** [comment]
You will need to run the "install.bat" file you find, then once you've run that you need to click the start server.bat file to start it up, it should be plug and play basically from then on. IF you are hosting it on another computer you will need to know that computer's IPV4 address in order to connect from your game. If you are hosting it on the same computer (Ensure you have at least 16+gb of ram as it will chew through it like no tomorrow) then use localhost as the IP address.
