### ISSUE TITLE
Crashing on mod loading screen.

### ISSUE THREAD

**Issue by TappyTapp** [Sunekaer/stoneBlock#683]
## Bug Report
At first, the game would open and I would be able to create a world but it would crash at the "Loading World" phase but after deleting and reinstalling the mod to try and fix this it doesn't even load past the forge mod loading screen where it gets stuck on the JEI mod. It Crashed on 

## Logs

* Client/Server Log: 
      "The game crashed whilst there was a severe problem during mod loading that has 
      caused the game to fail
      The game crashed whilst there was a severe problem during mod loading that has caused the game 
      to fail
      Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just 
      Enough Items (jei)"
* Crash Log: https://paste.feed-the-beast.com/view/92bb2e17

## Client Information

* Modpack Version: 1.0.31
* Server/LAN/Single Player: Single Player
* Optifine Installed: ?
* Shaders Enabled: ?

**Comment by Tommsy64** [comment]
This line `java.lang.OutOfMemoryError: GC overhead limit exceeded` means that the game is crashing because the java garbage collector is thrashing (i.e., spending more than 98% of the time freeing memory instead of running the program). This is happening because the JVM is running out of RAM.

This line `JVM Flags: 4 total; ... -Xmx3072m -Xms256m ...` shows that the game is being launched with only 3 gigabytes maximum of RAM.

In the Twitch settings, make sure the amount of RAM is at least 5 or 6 gigabytes. 8 is ideal.

![image](https://user-images.githubusercontent.com/3900951/49124859-f6cff580-f28b-11e8-94f9-cda34e3021e9.png)
