### ISSUE TITLE
I'm Not Quite Sure What is Wrong. 

### ISSUE THREAD

**Issue by NyteDarkDragon** [Sunekaer/stoneBlock#726]
##Crash Log (No Server log bc sp)
https://paste.feed-the-beast.com/view/133046b7
##Bug Report
It crashes every time before I even hit the menu screen

## Client Information
* Modpack Version: Mc-Forge 14.23.5.2768
* Server/LAN/Single Player: Single Player
* Optifine Installed: No
* Shaders Enabled: No

**Comment by Tommsy64** [comment]
`Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`
[My game is crashing on startup/freezing during world load, what do I do? (Or alternatively, how do I allocate the minimum 4 gigabytes of RAM?)](https://github.com/Sunekaer/stoneBlock#my-game-is-crashing-on-startupfreezing-during-world-load-what-do-i-do-or-alternatively-how-do-i-allocate-the-minimum-4-gigabytes-of-ram)
