### ISSUE TITLE
Mac OSX  game crash report. 

### ISSUE THREAD

**Issue by Kilown** [Sunekaer/stoneBlock#732]
## Bug Report
Just downloaded the game on Twitch and trying to launch it and it crashes please see report

## Steps to Reproduce (for bugs)

1. Click Play on twitch
2.*Loads Java*
3. Click Play on Java chuck 
4. Crash

*Please see logs sent to http://paste.feed-the-beast.com/ 

## Logs
Link1: 
https://paste.feed-the-beast.com/view/3240244f
Link2:
https://paste.feed-the-beast.com/view/3e9c4264
Link3: 
https://paste.feed-the-beast.com/view/58ff2f5e

## Client Information

* Modpack Version: 1.0.31 (current)
* Server/LAN/Single Player: Single Player 
* Optifine Installed: ? 
* Shaders Enabled: ?

**Comment by Tommsy64** [comment]
`Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`
[My game is crashing on startup/freezing during world load, what do I do? (Or alternatively, how do I allocate the minimum 4 gigabytes of RAM?)](https://github.com/Sunekaer/stoneBlock#my-game-is-crashing-on-startupfreezing-during-world-load-what-do-i-do-or-alternatively-how-do-i-allocate-the-minimum-4-gigabytes-of-ram)
