### ISSUE TITLE
Computercraft VS Opencomputer 

### ISSUE THREAD

**Issue by henkoe** [Sunekaer/stoneBlock#74]
## Context
i would love to see opencomputer to be added to the modpack instead of computercraft 
compercraft is outdated and missing most  Feature 

where opencomputers has more to offer 

## Mod Details
* Name: OpenComputers
* CurseForge Link:https://minecraft.curseforge.com/projects/opencomputers

**Comment by OfficialStamper** [comment]
I use ComputerCraft extensively in the pack, I would rather see mod _Plethora Peripherals_ added so CC has more functionality, or add both Plethora AND OC.
https://minecraft.curseforge.com/projects/plethora-peripherals

**Comment by cyb0124** [comment]
Computercraft lacks the functionality to interact with most modded/vanilla blocks, making it somehow useless for base control/automation other than reactor control. It can't even list the items in a vanilla chest! Also, popular mods like RFTools, Refined Storage and Immersive Engineering all provide OC api rather than CC api. So, please either switch to OC or add Plethora as OfficialStamper suggested.

**Comment by Sunekaer** [comment]
at this point of the pack im not gonna change out mods sorry mate
