### ISSUE TITLE
Games Freezes when shift clicking in to generator

### ISSUE THREAD

**Issue by FuzzyM0nst3r** [Sunekaer/stoneBlock#767]
sorry for the short description but I'm currently streaming and both me and one of my subs have been affected on the sub server

## Bug Report
Extra Utilities 2

## Steps to Reproduce (for bugs)

1.shift clicking in to a Furnace generator
2.

## Logs
No log as I have to force quit MC

## Client Information

* Modpack Version:1.0.32
* Server/LAN/Single Player:Server
* Optifine Installed:
* Shaders Enabled:

**Comment by Gunner76th** [comment]
This bug is an issue with Extra Utilities 2 and not with this modpack https://github.com/rwtema/Extra-Utilities-2-Source/issues/254

This bug has already been reported to Extra Utilities 2 github. Until Extra Utilities 2 is updated to resolve this issue, the only solution to this is to refrain from shift clicking into any Extra Utilities machines.
